version: '3'
services:
  app:
    build: .
    container_name: "nlccoc"
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - ${PWD}/app:${PWD}/app
    ports:
      - "3000:3000"
    depends_on: 
      - postgres
      - mongodb
    links: 
      - postgres:postgres
      - mongodb:mongodb
  postgres:
    image: postgres:latest
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=example
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=test
      - MONGO_INITDB_DATABASE=mydb_test
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
volumes: 
  app: